defaultBaseImage: cgr.dev/chainguard/static
defaultPlatforms:
# possible values: all, linux/s390x, linux/arm64, linux/arm/v7, linux/ppc64le, linux/amd64
- linux/arm64
- linux/arm/v7
- linux/amd64
builds:
- id: alertmanager-uptime-kuma-push
  main: ./cmd/pusher
  flags:
  - -tags
  - netgo
  ldflags:
  - '{{ if index .Env "LD_FLAGS" }}{{ .Env.LD_FLAGS }}{{ end }}'
